 PROGRAM UL1088(INPUT,OUTPUT);
 VAR
	  D,E,WD,WE,F,H:LONGINT;
	  PD,PE:ARRAY [1..100] OF LONGINT;
 PROCEDURE INIT;
	BEGIN
	  READLN(D,E,F,WD,WE,H);
	END;
 PROCEDURE MAIN;
	VAR
	  I,L,G:LONGINT;
	BEGIN
	  IF F=0 THEN
		BEGIN
		  WRITELN('YES');
		  EXIT;
		END;
	  DEC(WD);
	  DEC(WE);
	  FILLCHAR(PD,SIZEOF(PD),0);
	  FILLCHAR(PE,SIZEOF(PE),0);
	  FOR I:=F DOWNTO 1 DO
		IF 1 SHL (I-1)<=WD THEN
		  BEGIN
			PD[F+1-I]:=1;
			DEC(WD,1 SHL (I-1));
		  END;
	  FOR I:=F DOWNTO 1 DO
		IF 1 SHL (I-1)<=WE THEN
		  BEGIN
			PE[F+1-I]:=1;
			DEC(WE,1 SHL(I-1));
		  END;
	  FOR I:=1 TO F DO
		IF (PD[I]<>PE[I]) OR (I>F-D) OR (I>F-E) THEN BREAK;
	  IF (I>0) AND NOT ((I=F) AND (PD[F]=PE[F])) THEN DEC(I);
	  G:=F*2-D-E-I*2;
	  IF G<=H THEN WRITELN('YES')
		ELSE WRITELN('NO');
	END;
 BEGIN
	  INIT;
	  MAIN;
 END.